services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./ml_training:/app/ml_training
      - ./backend/models:/app/backend/models

    command: >
      bash -c "
      if [ ! -f 'ml_training/rf_model.pkl' ]; then
        echo '🚀 INITIALIZING FRESH ML MODELS FOR DEMO...';
        python ml_training/Train_Universal.py --fast;
      fi &&
      echo '🟢 STARTING GUNICORN SERVER...' &&
      gunicorn -k uvicorn.workers.UvicornWorker -t 600 -w 1 -b 0.0.0.0:8000 backend.main:app
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
