import requests
import json
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FRONTEND_TAXONOMY_PATH = os.path.abspath(os.path.join(BASE_DIR, "..", "frontend", "src", "javascript", "taxonomy.js"))

# 🛡️ ENTERPRISE FAILOVER CACHE
# If the Mozilla API goes down or blocks the request, the system falls back to this cache automatically.
FALLBACK_TAXONOMY = {
    "DevTools": {
        "A-M": ["Console", "Debugger", "General", "Inspector", "JSON Viewer", "Marionette Client and Harness"],
        "N-Z": ["Netmonitor", "Style Editor", "View Source", "geckodriver", "web-platform-tests"]
    },
    "Layout": {
        "A-M": ["CSS Parsing and Computation", "CSS Transitions and Animations", "Layout", "Layout: Flexbox",
                "Layout: Grid", "MathML"],
        "N-Z": ["Print Preview", "Printing: Output", "Printing: Setup", "SVG"]
    },
    "Networking": {
        "A-M": ["Cache", "Certificates", "Cookies", "DNS", "HTTP"],
        "N-Z": ["TLS/SSL", "WebSockets"]
    },
    "Frontend": {
        "A-M": ["Accessibility", "Address Bar", "Bookmarks", "Menus"],
        "N-Z": ["Screen Readers", "Tabs", "Theme"]
    },
    "Core": {
        "A-M": ["DOM Core", "DOM Events", "DOM Mutation", "Garbage Collection"],
        "N-Z": ["SpiderMonkey", "WASM"]
    }
}

FALLBACK_DESCRIPTIONS = {
    "DevTools": "Tools utilized by web developers to debug, inspect, and profile web applications.",
    "Layout": "The engine responsible for parsing HTML/CSS and calculating the visual geometry of the page.",
    "Networking": "Handles all HTTP, DNS, caching, and lower-level socket connections.",
    "Frontend": "The user-facing Firefox interface, including tabs, the URL bar, and bookmarking systems.",
    "Core": "The deep browser engine, including the SpiderMonkey JavaScript compiler and DOM manipulation."
}


def fetch_and_build_taxonomy():
    print("📡 [ETL PIPELINE] Connecting to Mozilla Bugzilla REST API...")

    taxonomy_data = {}
    team_descriptions = {}
    success = False

    try:
        # Added User-Agent and specific include_fields to prevent Mozilla from blocking or truncating the javascript
        url = "https://bugzilla.mozilla.org/rest/product?names=Firefox,Core,DevTools,Toolkit,NSS&include_fields=name,description,components.name,components.is_active"
        headers = {'User-Agent': 'BugPriorityOS-SeniorDesignProject/1.0'}

        response = requests.get(url, headers=headers, timeout=10)
        response.raise_for_status()
        raw_data = response.json()

        products = raw_data.get("products", [])
        if not products:
            raise ValueError("Mozilla API returned an empty product list.")

        for product in products:
            team_name = product.get("name")
            description = product.get("description", "Core subsystem architecture.")
            team_descriptions[team_name] = description

            taxonomy_data[team_name] = {"A-M": [], "N-Z": []}

            for comp in product.get("components", []):
                comp_name = comp.get("name")
                if not comp.get("is_active"):
                    continue
                if comp_name[0].upper() < 'N':
                    taxonomy_data[team_name]["A-M"].append(comp_name)
                else:
                    taxonomy_data[team_name]["N-Z"].append(comp_name)

        # Remove empty teams/categories
        for team in list(taxonomy_data.keys()):
            taxonomy_data[team] = {k: v for k, v in taxonomy_data[team].items() if v}
            if not taxonomy_data[team]:
                del taxonomy_data[team]

        if len(taxonomy_data) > 0:
            success = True
            print("✅ [ETL PIPELINE] Live Data Extracted & Transformed successfully!")
        else:
            raise ValueError("All components filtered out. Resulting javascript was empty.")

    except Exception as e:
        print(f"⚠️ [ETL PIPELINE] Live sync failed: {e}")
        print("🔄 [ETL PIPELINE] Engaging Enterprise Fallback Cache (Failover Mode)...")
        taxonomy_data = FALLBACK_TAXONOMY
        team_descriptions = FALLBACK_DESCRIPTIONS
        success = True

    # 3. LOAD: Write it securely to the React frontend
    if success:
        print(f"💾 [ETL PIPELINE] Writing taxonomy to {FRONTEND_TAXONOMY_PATH}")

        js_content = f"""// AUTO-GENERATED BY BACKEND ETL PIPELINE
// Do not edit manually. Data synchronized directly from Bugzilla REST API.

export const mozillaTaxonomy = {json.dumps(taxonomy_data, indent=2)};

export const teamDescriptions = {json.dumps(team_descriptions, indent=2)};
"""
        os.makedirs(os.path.dirname(FRONTEND_TAXONOMY_PATH), exist_ok=True)
        with open(FRONTEND_TAXONOMY_PATH, "w", encoding="utf-8") as f:
            f.write(js_content)

        print("✅ [ETL PIPELINE] Frontend Sync Complete!")


if __name__ == "__main__":
    fetch_and_build_taxonomy()