// AUTO-GENERATED BY BACKEND ETL PIPELINE
// Do not edit manually. Data synchronized directly from Bugzilla REST API.

export const mozillaTaxonomy = {
  "DevTools": {
    "A-M": [
      "Console",
      "Debugger",
      "General",
      "Inspector",
      "JSON Viewer",
      "Marionette Client and Harness"
    ],
    "N-Z": [
      "Netmonitor",
      "Style Editor",
      "View Source",
      "geckodriver",
      "web-platform-tests"
    ]
  },
  "Layout": {
    "A-M": [
      "CSS Parsing and Computation",
      "CSS Transitions and Animations",
      "Layout",
      "Layout: Flexbox",
      "Layout: Grid",
      "MathML"
    ],
    "N-Z": [
      "Print Preview",
      "Printing: Output",
      "Printing: Setup",
      "SVG"
    ]
  },
  "Networking": {
    "A-M": [
      "Cache",
      "Certificates",
      "Cookies",
      "DNS",
      "HTTP"
    ],
    "N-Z": [
      "TLS/SSL",
      "WebSockets"
    ]
  },
  "Frontend": {
    "A-M": [
      "Accessibility",
      "Address Bar",
      "Bookmarks",
      "Menus"
    ],
    "N-Z": [
      "Screen Readers",
      "Tabs",
      "Theme"
    ]
  },
  "Core": {
    "A-M": [
      "DOM Core",
      "DOM Events",
      "DOM Mutation",
      "Garbage Collection"
    ],
    "N-Z": [
      "SpiderMonkey",
      "WASM"
    ]
  }
};

export const teamDescriptions = {
  "DevTools": "Tools utilized by web developers to debug, inspect, and profile web applications.",
  "Layout": "The engine responsible for parsing HTML/CSS and calculating the visual geometry of the page.",
  "Networking": "Handles all HTTP, DNS, caching, and lower-level socket connections.",
  "Frontend": "The user-facing Firefox interface, including tabs, the URL bar, and bookmarking systems.",
  "Core": "The deep browser engine, including the SpiderMonkey JavaScript compiler and DOM manipulation."
};
