name: CI Build Pipeline

on:
  push:
    branches:
      - 'amar-branch'
      - 'anu-branch'
      - 'stage'
      - 'main'
      - 'production'
  pull_request:
    branches:
      - 'stage'
      - 'main'
      - 'production'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Dummy Environment File
        run: |
          mkdir -p backend
          echo "SUPABASE_URL=dummy_url" > backend/.env
          echo "SUPABASE_KEY=dummy_key" >> backend/.env

      - name: Build Docker Images
        run: docker compose build